---
title: "ANALISIS EXPLORATORIO TIC DE LOS DATOS"
author: "Dario Quishpe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(sf)
library(leaflet)
library(deldir)
library(spatstat)
library(tsibble)
library(tseries)

library(fpp3)
library(forecast)
library(fpp2)
library(TSA)
library(grid)
library(gridExtra)
pacman::p_load(tidyverse,sf,mapview)
```

### Estadistica descriptiva de los datos  


```{r}
base<-read.csv("obs_data_112Valencia (1).csv")
head(base$crime_date)
tail(base$crime_date)

base<-base |> filter(year<=2019)
head(base$crime_date)
tail(base$crime_date)
base
#view(base)
```



```{r}
(summary(base))
str(base)

```

```{r}
apply(is.na(base), 2, mean)
```
```{r}
BASE<-read.csv("obs_data_112Valencia (1).csv", sep=",", header=TRUE) 
puntos<-BASE|>filter(year<=2019) |> st_as_sf(coords=c("crime_lon","crime_lat"),crs= 4258)

#mapview(puntos, map.types = "CartoDB.Voyager")

puntos
```
```{r}


ventana_sin_z <- st_zm(ventana)
barrio<- st_read("barris-barrios/barris-barrios.shp",quiet=TRUE)
barrio<-barrio |> filter(coddistbar=="112")
#barrio <- st_transform(barrio, crs = st_crs("EPSG:32630"))
barrio_sin_z <- st_zm(barrio)
# Crear el mapa
mapa <- leaflet() %>%
  addTiles() %>% addPolygons(data = ventana_sin_z,color = "black",opacity = 0.4,
  dashArray = "2",   weight = 3) |> 
  addPolygons(data = barrio_sin_z,color = "red",opacity = 0.5,
  dashArray = "2",   weight = 3) 

# Visualizar el mapa
mapa
```


```{r}


ventana_sin_z <- st_zm(ventana)
barrio<- st_read("barris-barrios/barris-barrios.shp",quiet=TRUE)
barrio<-barrio |> filter(coddistbar=="112")
#barrio <- st_transform(barrio, crs = st_crs("EPSG:32630"))
barrio_sin_z <- st_zm(barrio)
# Crear el mapa
mapa <- leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = puntos, color = "#2DBCFA", radius = 0.01)

# Agregar los límites de la ciudad al mapa
mapa1 <- mapa %>% addPolygons(data = ventana_sin_z,
  opacity = 1,
  color = "black",
  dashArray = "3",
  fillOpacity = 0.2, weight = 5)

mapa1
```

```{r}
ventana_sin_z <- st_zm(ventana)
barrio<- st_read("barris-barrios/barris-barrios.shp",quiet=TRUE)
barrio<-barrio |> filter(coddistbar=="112")
#barrio <- st_transform(barrio, crs = st_crs("EPSG:32630"))
barrio_sin_z <- st_zm(barrio)
# Crear el mapa
mapa <- leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = puntos, color = "#2DBCFA", radius = 0.05)

# Agregar los límites de la ciudad al mapa
mapa1 <- mapa %>% addPolygons(data = ventana_sin_z,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.2, weight = 5)

mapa2<-mapa1 |> addPolygons(data = barrio_sin_z,
  opacity = 1,
  color = "red",
  dashArray = "3",
  fillOpacity = 0.5,   weight = 6) 

# Visualizar el mapa
mapa2
```

```{r}

```

```{r}
#DIVISIONES DE DISTRTOS ORIGINALES 
#library(sf)
ventana <- st_read("shape files-20221031T083303Z-001/shape files/valencia_outline.shp",quiet=TRUE)
y <- st_read("shape files-20221031T083303Z-001/shape files/valencia_road.shp",quiet=TRUE)

#ggplot()+geom_sf(data = x)+geom_sf(data = y)+geom_sf(data = puntos,aes())+scale_x_continuous()
#y<-st_read("ca_municipios_20231105/ca_municipios_20231105.shp")
#view(x)
#ggplot() + geom_sf(data = x, fill="darkseagreen")
#x <- st_read("drive-download-20231208T164315Z-001/ecuador.shp",quiet=TRUE)
#ventana<-x |> filter(NOMBRE=="VALENCIA")  

#Filtro de base para presentar datos espaciales 
  
puntos_grafica<-puntos 
dim(puntos_grafica)
dim(puntos)
ggplot()+geom_sf(data = ventana,color="black",size=5)+geom_sf(data = y,color="black")+geom_sf(data = puntos_grafica,aes(),size=0.1,color="yellow")+scale_x_continuous()+theme(plot.margin = margin(1, 1, 1, 1, "mm"),
        panel.spacing = unit(1, "lines"))

puntos_grafica<- puntos_grafica |> mutate(crime_type=ifelse(crime_type=="Agresion","Agresión",ifelse(crime_type=="Sustraccion","Sustracción",crime_type)))

ggplot() +
  geom_sf(data = ventana, color = "black", size = 2) +
  geom_sf(data = y, color = "black") +
  geom_sf(data = puntos_grafica, aes(), size = 0.1, color = "yellow") +
  facet_wrap(~crime_type, nrow = 1, ncol = 4) +
  theme(
    axis.text.x = element_text(size=rel(1.2),angle = 90, vjust = 0.5, hjust = 1, face = "bold"),
    axis.text.y = element_text(size=rel(1.2),face = "bold"),
    strip.text = element_text(size = rel(1.2)),  # Aumenta el tamaño del texto de cada categoría
    strip.background = element_rect(fill = "lightblue")
  )


```
```{r}

#tablita de frecuencias 
tabla<-base |> group_by(year,crime_type) |> summarise(Tot=n()) |> 
            mutate(Porcentaje=round(Tot/sum(Tot)*100,2))


tabla <- tabla[order(-tabla$Tot), ]
tabla<-tabla |>  mutate(crime_type=ifelse(crime_type=="Agresion","Agresión",ifelse(crime_type=="Sustraccion","Sustracción",crime_type)))

tabla$crime_type <- factor(tabla$crime_type, levels = c("Agresión", "AlarmasMujer", "Sustracción", "Otros"))

# Crear una paleta de colores
color_palette <- colorRampPalette(c("yellow", "orange", "red"))

# Crear el gráfico de barras con colores asignados según la altura de las barras
# Crear el gráfico de barras con colores asignados según la altura de las barras
ggplot(tabla, aes(x = crime_type, y = Tot, fill = Tot)) +
  geom_bar(color = "black", width = 0.9, stat = "identity", position = position_dodge()) +
  scale_fill_gradientn(colours = color_palette(nrow(tabla))) + 
  ylim(c(0, max(tabla$Tot) * 1.1)) + 
  labs(x = "Tipo de delitos", y = "Número de delitos", fill = "") +
  geom_text(aes(label = paste0(Tot, " ", "", "(", Porcentaje, "%", ")")),
            vjust = -0.9, color = "black", hjust = 0.5,
            position = position_dodge(0.9), angle = 0, size = 4.0) +
  theme(
    axis.text.x = element_text(size = rel(1), angle = 0, vjust = 1, hjust = 0.5, face = "bold"),
    axis.text.y = element_text(size = rel(1), face = "bold"),
    axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)),
    axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)),
    strip.text = element_text(size = rel(1.2)),  # Aumenta el tamaño del texto de cada categoría
    strip.background = element_rect(fill = "lightblue")
  )





```


```{r}
tabla_agresion <- tabla |> filter(crime_type == "Agresion")

# Verificar si hay datos para graficar
if(nrow(tabla_agresion) > 0){
  # Crear una paleta de colores
  color_palette <- colorRampPalette(c("yellow", "orange", "red"))
  
  # Crear el gráfico de barras
  ggplot(tabla_agresion, aes(x = factor(year), y = Tot, fill = Tot)) +
    geom_bar(color = "black", width = 0.9, stat = "identity", position = position_dodge()) +
    scale_fill_gradientn(colours = color_palette(nrow(tabla_agresion))) + 
    ylim(c(0, max(tabla_agresion$Tot) * 1.1)) + 
    labs(x = "Año", y = "Número de agresiones") +
    geom_text(aes(label = paste0(Tot)),
              vjust = -0.9, color = "black", hjust = 0.5,
              position = position_dodge(0.9), angle = 0, size = 4.0) +
    theme(
      axis.text.x = element_text(size = rel(1), angle = 0, vjust = 1, hjust = 0.5, face = "bold"),
      axis.text.y = element_text(size = rel(1), face = "bold"),
      axis.title.x = element_text(size = rel(1.2), face = "bold", margin = margin(t = 15, r = 0, b = 0, l = 0)),
      axis.title.y = element_text(size = rel(1.2), face = "bold", margin = margin(t = 0, r = 15, b = 0, l = 0)),
      legend.position = "none",  # Eliminar la leyenda
      strip.text = element_text(size = rel(0.1)),  # Aumenta el tamaño del texto de cada categoría
      strip.background = element_rect(fill = "lightblue")
    )
} else {
  print("No hay datos de agresiones para graficar.")
}
```
```{r}
st<-base |> mutate(crime_date=as.Date(crime_date,format = "%m/%d/%Y"))
stmy<-st |>mutate(anio_mes=format(crime_date,"%Y-%m")) |> 
        group_by(anio_mes) |> summarise(Numero_de_Registros=n())

stmy$Tiempo <-yearmonth(stmy$anio_mes)
ST<-stmy |>  as_tsibble(index = Tiempo) 

ST %>%
  autoplot() +
  geom_point(color = "black", fill = "yellow", shape = 21, size = 3) +  # Puntos con contorno negro y relleno amarillo
  geom_line(color = "black", size = 1) +  # Línea más gruesa
  labs(x = "Fecha (Año-Mes)", y = "Número de Registros") +  # Cambiar títulos de los ejes
  scale_x_yearmonth(breaks = "11 months", date_labels = "%Y-%m") +  # Mostrar más valores en el eje x
  theme_bw() +
  theme(
    axis.title.x = element_text(size = 10, face = "bold"),  # Aumentar tamaño del título del eje x
    axis.title.y = element_text(size = 10, face = "bold"),  # Aumentar tamaño del título del eje y
    axis.text.x = element_text(angle = 90, hjust = 1),  # Rotar los textos del eje x para mejor legibilidad
    legend.position = "none"  # Quitar la leyenda
  )
```


```{r}
st<-base |> mutate(crime_date=as.Date(crime_date,format = "%m/%d/%Y"))
stmy<-st |>mutate(anio_mes=format(crime_date,"%Y-%m")) |> 
        group_by(anio_mes) |> summarise(Numero_de_Registros=n())

stmy$Tiempo <-yearmonth(stmy$anio_mes)
ST<-stmy |>  as_tsibble(index = Tiempo) |> select(Tiempo,Numero_de_Registros)
ST %>%
  autoplot() +
  geom_point(color = "black") +  
  geom_line(color = "blue") +    
  theme_light()  
```

```{r}
diadelasemana<-base |> group_by(week_day_name) |> summarise(Observaciones=n()) |> arrange(Observaciones)
horadeldia<-base |> group_by(crime_hour) |> summarise(Observaciones=n()) |> 
                                          arrange(crime_hour) |> 
                                          mutate(Porcentaje=round(Observaciones/sum(Observaciones)*100,2)) |> 
                                          mutate(UBICACIÓN="CIUDAD DE VALENCIA")

horadeldiabarrio<-puntos_barrio |> group_by(crime_hour) |> summarise(Observaciones=n()) |>
                                                            arrange(crime_hour) |> 
                                                             mutate(Porcentaje=round(Observaciones/sum(Observaciones)*100,2)) |> 
                                                             mutate(UBICACIÓN="EL CABANYAL") 

horadeldiabarrio<-as.data.frame(horadeldiabarrio)
horadeldiabarrio<-horadeldiabarrio |> select(crime_hour)
barras_horario<-rbind(horadeldia,horadeldiabarrio)
suma<-horadeldia |> filter(crime_hour>=18| crime_hour<=1)
sum(suma$Observaciones)
sum(horadeldia$Observaciones)
diadelasemana$week_day_name <- factor(diadelasemana$week_day_name, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"),
                              labels = c("Lun", "Mar", "Miér", "Jue", "Vier", "Sáb", "Dom"))

color_palette <- colorRampPalette(c("yellow", "orange","red"))

dias<-ggplot(diadelasemana, aes(x = week_day_name, y = Observaciones, fill = Observaciones)) +
  geom_bar(stat = "identity") +geom_text(aes(label = Observaciones), vjust = -0, color = "black", size = 3)+
  scale_fill_gradientn(colours = color_palette(nrow(diadelasemana))) + 
  labs(x = "Día de la semana", y = "Observaciones") +
  scale_x_discrete(labels = function(x) gsub("Tuesday", "Mar", gsub("Monday", "Lun", gsub("Wednesday", "Miér", gsub("Thursday", "Jue", gsub("Friday", "Vier", gsub("Saturday", "Sáb", gsub("Sunday", "Dom", x)))))))) +
  theme_minimal() +theme(plot.margin = margin(5, 0, 0, 0, "mm"),
        panel.spacing = unit(10, "lines"))+
  theme(axis.text.x = element_text(angle = 360, hjust = 1),legend.position = "none") 
dias
```




```{r}



# Definir paletas de colores
palette_ubicacion1 <- c("yellow", "red")
palette_ubicacion2 <- c("#CC3333", "#FF6666")

# Crear el gráfico
horas <- ggplot(barras_horario, aes(x = crime_hour, y = Porcentaje, fill = UBICACIÓN)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_text(aes(label = Porcentaje), vjust = 0.3, color = "black", size = 4,angle=90, 
            position = position_dodge(width = 0.9), hjust = -0.2) +
  scale_fill_manual(values = c(palette_ubicacion1, palette_ubicacion2)) + 
  labs(x = "Hora del día", y = "Porcentaje %", fill = "Ubicación") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 10, face = "bold"),  # Texto horizontal y centrado
    axis.text.y = element_text(size = 13, face = "bold"),  # Texto en el eje Y en negrita
    axis.title = element_text(size = 13, face = "bold"),   # Títulos en negrita
    legend.position = "top",  # Mover la leyenda a la parte superior
    legend.text = element_text(size = 11),  # Reducir tamaño del texto de la leyenda
    legend.title = element_text(size = 10),  # Reducir tamaño del título de la leyenda
    plot.margin = margin(4, 0, 0, 0, "mm"),  # Ajustar márgenes del gráfico
    panel.spacing = unit(4, "lines")
  )

# Mostrar el gráfico
print(horas)
```
```{r}

# Crear la paleta de colores
color_palette <- colorRampPalette(c("yellow", "orange", "red"))

# Añadir una columna para el color de las barras según la paleta
barras_horario <- barras_horario %>%
  mutate(Color = color_palette(nrow(barras_horario)))

# Crear el gráfico
horas <- ggplot(horadeldia, aes(x = as.factor(crime_hour), y = Observaciones, fill = Observaciones)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Observaciones), 
            vjust = -0, hjust = 1, angle = 90, color = "black", size = 3) +
  scale_fill_gradientn(colours = color_palette(nrow(barras_horario))) + 
  labs(x = "Hora del día", y = " Observaciones") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 10),  # Texto horizontal y centrado
    axis.text.y = element_text(size = 10),  # Texto en el eje Y en negrita
    axis.title = element_text(size = 10 ),   # Títulos en negrita
    plot.margin = margin(5, 0, 0, 0, "mm"),  # Ajustar márgenes del gráfico
    panel.spacing = unit(4, "lines"),
    legend.position = "none"  # Eliminar la leyenda
  )

# Mostrar el gráfico
print(horas)
```

```{r}

grid.arrange(dias,horas)

```

